# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4737bc83f2f3dd3ae8fc73e43b8a15f09b39d915aa5aca5390a7231ee2efe1652429566fd85184c656e5dee8c80335896fff40f408c13977fb6e79c3ce388209

test:
  secret_key_base: 14e9a34b88f8b790aacef6d9e9fe665a534d7ee28b6d3ee76090d0ef749c83eb3ed3ccead84ff306293745d1202c72cc653178ab9a5304250fe522a406f76262

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
